name: Build and Publish

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: '16'
          scope: '@lunarbytellc'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to GitHub Packages
        run:
          npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
